### ISSUE TITLE
usergroups.php

### ISSUE THREAD

**Issue by Technologx2013** [sctigercat1/Cydia-UDID-Protected-Repo-PHP#11]
Warning: file_get_contents(/beta_mode.json) [function.file-get-contents]: failed to open stream: No such file or directory in apt.technologx.pw/vip/usergroups.php on line 12

Warning: array_combine() [function.array-combine]: Both parameters should have at least 1 element in apt.technologx.pw/vip/usergroups.php on line 70

**Comment by shrijitsingh99** [comment]
U can fix first error by visiting this link
https://github.com/sctigercat1/Cydia-UDID-Protected-Repo-PHP/pull/5#issuecomment-69599688

**Comment by shrijitsingh99** [comment]
U can fix first error by visiting this link
https://github.com/sctigercat1/Cydia-UDID-Protected-Repo-PHP/pull/5#issuecomment-69599688

**Comment by shrijitsingh99** [comment]
U can fix first error by visiting this link
https://github.com/sctigercat1/Cydia-UDID-Protected-Repo-PHP/pull/5#issuecomment-69599688

**Comment by sctigercat1** [comment]
I'll push that fix later today (I don't have time now).

**Comment by D3ATH2020** [comment]
I would appreciated it I really like what you did with the script it has a nice clean UI if you don't mind when you get it updated can you email me at technologx@technologx.pw?

**Comment by Technologx2013** [comment]
This $BetaModeFromJSON = json_decode(file_get_contents(realpath(__DIR__ . "/beta_mode.json")), true); fixed line 12 error but I still have the line 70 error.

**Comment by sctigercat1** [comment]
@Technologx2013 does the commit bffddca fix both errors?

**Comment by Technologx2013** [comment]
@sctigercat1 Now I"m getting Warning: array_combine() [function.array-combine]: Both parameters should have at least 1 element in apt.technologx.pw/vip/usergroups.php on line 71 by the way I can't seem to style the admin.php at all I've tried over and over to turn the links into buttons.

**Comment by sctigercat1** [comment]
@Technologx2013 Oh wow, I messed up there. :P

Commit 0e637a2 *better* fix this problem as that was just a little mistake in the previous one. ;)

Oh, and with the buttons/links...which ones were you trying to change? You should just be able to do < button></button>, but note that in the code there's an if statement that checks whether or not you're on an iOS device. Just make sure you aren't putting your code there lol.

**Comment by Technologx2013** [comment]
I got the iOS to work I just need to do the same with the Desktop version

**Comment by Technologx2013** [comment]
That worked do think I could possibly get your email address I'd like to help you with the UI on this?

**Comment by sctigercat1** [comment]
I honestly haven't had much time as of late (and I probably won't for a little while longer).

However, @shrijitsingh99 has mentioned that s/he also would like to work on the CSS/UI, so maybe you both could work together and submit a pull request for the UI when you've got something.

I could make a new branch and store the in-progress UI there as you submit pull requests with different objectives.

Again, I'm sorry I won't be able to help you much, my life has just been pretty busy. Even so, I look forward to seeing what you may create in the future!
