### ISSUE TITLE
When i add my repo i get /bin/bzip2 returned an error code (2)

### ISSUE THREAD

**Issue by ThirdEyeRuler** [sctigercat1/Cydia-UDID-Protected-Repo-PHP#14]
i followed everything from the github tutorial but it wont work.  and when i upload a deb from the admin page it doesnt add it to the debs folder.

**Comment by Technologx2013** [comment]
Create a topic on my forum and post screenshots so I can see what exactly is going on. http://technologx.pw/index.php?/r/1




Kevin Nye /Owner/Founder 
technologx@technologx.pw

Technologx 
http://technologx.pw

**Comment by ThirdEyeRuler** [comment]
http://technologx.pw/topic/473-cant-get-repo-working-proccess-error/

**Comment by Technologx2013** [comment]
I replied to your topic.




Kevin Nye /Owner/Founder 
technologx@technologx.pw

Technologx 
http://technologx.pw

**Comment by sctigercat1** [comment]
Hey there! I saw your posts on the links above.

First of all, what server are you running this on?

**Comment by ThirdEyeRuler** [comment]
Ubuntu 14.04

**Comment by sctigercat1** [comment]
Alright, so I'll assume you've installed apache and php and the like.

You need the bzip2 php module installed and activated also, do you have that?

**Comment by ThirdEyeRuler** [comment]
Yes I have had a previous repo on

**Comment by ThirdEyeRuler** [comment]
Yes I have had a previous repo on

**Comment by ThirdEyeRuler** [comment]
hmmm.. seems like bzip2 php module isint on O.o ..

Could you help me out installing it on ubunutu? i am having trouble

**Comment by ThirdEyeRuler** [comment]
php -i | grep 'bzip'
Registered PHP Streams => https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
Registered Stream Filters => zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk
Stream Wrapper support => compress.bzip2://
Stream Filter support => bzip2.decompress, bzip2.compress
bzip2 compression => enabled
Libzip version => 0.10.1
 i believe it is enabled sorry ..

**Comment by ThirdEyeRuler** [comment]
I fixed it. Packages, Release, and Packages.bz2 files were missing. I also
had to chmod 777 repofiles and the ones I just listed for it to work.

**Comment by sctigercat1** [comment]
Ah alright, glad you got it working. :)
