### ISSUE TITLE
Sizes

### ISSUE THREAD

**Issue by alxtr1bal** [sctigercat1/Cydia-UDID-Protected-Repo-PHP#6]
Hi ! I just wanted to know how to fill the Size, and Installed-Size?

**Comment by sctigercat1** [comment]
Size is the size in bytes of the packaged .deb file.

As for installed-size...that's something I don't use so I wouldn't know much about it. Some users reported that using this would fix upgrade loops, but I personally haven't seen this in action. Perhaps someone else or a Google search can help better explain this!

You can always leave any of the input boxes blank; if they don't contain any text, it won't end up in the control file. So, if you don't want to use it (or don't know how), just don't put anything there. :)

**Comment by alxtr1bal** [comment]
I keep getting a size mismatch on cydia, after adding my repo and trying to download :( 
Entering sizes , or not …
(I’m on a mac)

**Comment by shrijitsingh99** [comment]
Well I get size mismatch error when the size u enter is different from the size of file

**Comment by shrijitsingh99** [comment]
Installed size is used to give user an idea how much space the file will take after installation

**Comment by sctigercat1** [comment]
@alxtr1bal I don't have a mac, but google resulted in this terminal command:

```stat -f%z filename.deb```

Run that with your file name and it *should* return the byte size of the file. Put that value in for Size and just ignore the other one.

Again, I can't confirm that this works, but who knows, maybe it will. :)

**Comment by alxtr1bal** [comment]
Yeah, this command works , i figured i could to a cmd + I also on the file, it gives the same size…

But i dont think this is my problem now :( 

May be a problem with dpkg-deb, i dont know yet

**Comment by sctigercat1** [comment]
Whoops, hit the wrong button lol.

At any rate, let me know if you've asked all your questions here since this issue is becoming something that's not related to this Cydia repo. ;)

**Comment by alxtr1bal** [comment]
Yeah I guess it was not related !
But thanks for your help anyway :-)
